=== arueckle/nothing-to-see-here/scripts/adapter.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://adapterhub.ml/adapter.schema.json",
    "type": "object",
    "title": "Adapter-Hub adapter entry",
    "required": [
        "_meta",
        "config",
        "hidden_size",
        "model_type",
        "name",
        "type"
    ],
    "additionalProperties": false,
    "properties": {
        "_meta": {
            "type": "object",
            "required": [
                "id",
                "author",
                "default_version",
                "files",
                "task",
                "subtask"
            ],
            "additionalProperties": true,
            "properties": {
                "id": {
                    "type": "string",
                    "minLength": 24,
                    "maxLength": 24
                },
                "author": {
                    "type": "string",
                    "minLength": 1
                },
                "email": {
                    "type": "string",
                    "format": "email"
                },
                "url": {
                    "type": "string",
                    "format": "uri"
                },
                "citation": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "default_version": {
                    "type": "string"
                },
                "files": {
                    "type": "object",
                    "minProperties": 1,
                    "additionalProperties": false,
                    "patternProperties": {
                        ".*": {
                            "type": "object",
                            "anyOf": [
                                {
                                    "required": [
                                        "url",
                                        "sha1"
                                    ]
                                },
                                {
                                    "required": [
                                        "url",
                                        "sha256"
                                    ]
                                }
                            ],
                            "additionalProperties": false,
                            "properties": {
                                "url": {
                                    "type": "string",
                                    "format": "uri"
                                },
                                "sha1": {
                                    "type": "string"
                                },
                                "sha256": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "task": {
                    "type": "string",
                    "minLength": 1
                },
                "subtask": {
                    "type": "string",
                    "minLength": 1
                },
                "score": {
                    "type": "number"
                }
            }
        },
        "config": {
            "type": ["object", "string"],
            "additionalProperties": true,
            "minProperties": 1,
            "minLength": 1
        },
        "hidden_size": {
            "type": "integer"
        },
        "model_type": {
            "type": "string",
            "minLength": 1
        },
        "name": {
            "type": "string",
            "minLength": 1
        },
        "type": {
            "type": "string",
            "minLength": 1
        }
    }
}

=== arueckle/nothing-to-see-here/repo/example-org/text_task-sst-bert-768-c315ba3bb3ccb683.json
{
  "_meta": {
    "author": "Example Org.",
    "citation": "@misc{pfeiffer2020adapterfusion,\r\n    title={AdapterFusion: Non-Destructive Task Composition for Transfer Learning},\r\n    author={Jonas Pfeiffer and Aishwarya Kamath and Andreas R\u00FCckl\u00E9 and Kyunghyun Cho and Iryna Gurevych},\r\n    year={2020},\r\n    eprint={2005.00247},\r\n    archivePrefix={arXiv},\r\n    primaryClass={cs.CL}\r\n}",
    "default_version": "1",
    "description": "MNLI task adapter in Pfeiffer architecture for BERT base.",
    "email": "mail@example.org",
    "files": {
      "1": {
        "sha1": "ee39c07db6f4545a8c1ca4098cd3f15275a3f6cd",
        "url": "http://adapter-hub.webredirect.org/repo/files/bert-768-text_task-sst-c315ba3bb3ccb683.zip"
      }
    },
    "id": "2f68aea9c315ba3bb3ccb683",
    "score": 0.90,
    "task": "sentiment",
    "subtask": "sst",
    "url": "https://example.org"
  },
  "config": {
    "LN_after": false,
    "LN_before": false,
    "MH_Adapter": false,
    "Output_Adapter": true,
    "adapter_residual_before_ln": false,
    "attention_type": "sent-lvl-dynamic",
    "new_attention_norm": false,
    "non_linearity": "relu",
    "original_ln_after": true,
    "original_ln_before": true,
    "reduction_factor": 16,
    "residual_before_ln": true
  },
  "hidden_size": 768,
  "model_type": "bert",
  "name": "sst",
  "type": "text_task"
}

=== arueckle/nothing-to-see-here/repo/example-org/bert_base_mnli.json
{
  "_meta": {
    "id": "0a505c7c11072812d9e5e08c",
    "author": "Example Org.",
    "email": "mail@example.org",
    "url": "https://example.org",
    "citation": "@misc{pfeiffer2020adapterfusion,\r\n    title={AdapterFusion: Non-Destructive Task Composition for Transfer Learning},\r\n    author={Jonas Pfeiffer and Aishwarya Kamath and Andreas R\u00FCckl\u00E9 and Kyunghyun Cho and Iryna Gurevych},\r\n    year={2020},\r\n    eprint={2005.00247},\r\n    archivePrefix={arXiv},\r\n    primaryClass={cs.CL}\r\n}",
    "description": "MNLI task adapter in Pfeiffer architecture for BERT base.",
    "default_version": "1",
    "files": {
      "1": {
        "url": "http://adapter-hub.webredirect.org/repo/files/bert-base-mnli-pfeiffer-v1.zip",
        "sha1": "37B93BA1EF3C7821F114FC792C590BD1548E9022"
      }
    },
    "task": "nli",
    "subtask": "multinli",
    "score": 0.90
  },
  "config": "pfeiffer",
  "hidden_size": 768,
  "model_type": "bert",
  "name": "multinli",
  "type": "text_task"
}
